name: pharmacie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  geolocator: ^10.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ”¥ Firebase (versions compatibles entre elles)
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.1

  # ğŸ¨ UI
  google_fonts: ^6.3.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


